// src/app.vue
<script lang="ts" setup>
import TWallpaper from '@twallpaper/vue'
import { onMounted, ref, watch } from 'vue'
import box from './components/box.vue'
import notification from './components/notification.vue'
import { BoxEnum, FruitGame } from './composables/use-game'
import { useNotification } from './composables/use-notification'
import type { TWallpaperOptions } from '@twallpaper/vue'
// eslint-disable-next-line ts/ban-ts-comment
// @ts-expect-error
import '@twallpaper/vue/css'

const STORAGE_KEY = 'fruitGameState'
const game = ref<FruitGame | null>(null)
const gameState = ref<'playing' | 'won' | 'lost'>('playing')
const { showNotification } = useNotification()
const attempts = ref(1)
const isButtonVisible = ref(false)

function loadGame() {
  const savedState = localStorage.getItem(STORAGE_KEY)
  if (savedState) {
    try {
      const json = JSON.parse(savedState)
      game.value = FruitGame.fromJSON(json.game)
      gameState.value = json.gameState
      attempts.value = json.attempts || 1
    } catch {
      game.value = new FruitGame()
      gameState.value = 'playing'
      attempts.value = 1
    }
  } else {
    game.value = new FruitGame()
    gameState.value = 'playing'
    attempts.value = 1
  }
}

onMounted(loadGame)

watch([game, gameState, attempts], () => {
  if (game.value) {
    const stateToSave = { game: game.value, gameState: gameState.value, attempts: attempts.value }
    localStorage.setItem(STORAGE_KEY, JSON.stringify(stateToSave))
  }
}, { deep: true })

function handleBoxClick(index: number) {
  if (!game.value || gameState.value !== 'playing') return
  try {
    game.value.openBox(index)
  } catch (error: any) {
    showNotification(error.message)
  }
  isButtonVisible.value = true
}

function handlePredictionChange(index: number, value: BoxEnum) {
  if (!game.value || gameState.value !== 'playing') return
  try {
    game.value.setPrediction(index, value)
  } catch (error: any) {
    showNotification(error.message)
  }
}

function handleCheck() {
  if (!game.value) return
  try {
    game.value.openRemainingBoxes()
    gameState.value = game.value.checkGameStatus()
  } catch (error: any) {
    showNotification(error.message)
  }
}

function handleRestart() {
  attempts.value++
  localStorage.removeItem(STORAGE_KEY)
  game.value = new FruitGame()
  gameState.value = 'playing'
  isButtonVisible.value = false
}

const canChangePrediction = ref(true)
const twallpaper = ref<InstanceType<typeof TWallpaper>>()
const options = ref<TWallpaperOptions>({
  animate: false,
  colors: [
    '#90E0EF',
    '#48CAE4',
    '#00B4D8',
    '#0096C7',
    '#0077B6',
    '#023E8A',
  ],
  pattern: {
    mask: false,
    opacity: 0.3,
    image: 'https://twallpaper.js.org/patterns/math.svg',
  },
})
</script>

<template>
  <div v-if="gameState === 'lost'" class="loss-screen fullscreen">
    <div style="display: flex; flex-direction: column; align-items: center;">
      <div class="text">
        Ты проиграл
      </div>
      <button class="button" @click="handleRestart">
        Начать заново
      </button>
    </div>
  </div>
  <div v-else-if="gameState === 'won'" class="win-screen fullscreen" style="display: flex; flex-direction: column; align-items: center;">
    <div class="text">
      Ты победил
    </div>
    <div class="text" style="font-size: clamp(32px, 5vw, 48px);">
      {{ `Попыток потрачено: ${attempts}` }}
    </div>
  </div>
  <div v-else class="fullscreen">
    <div class="centered-container">
      <p style="font-size: clamp(2rem, 3.5vw, 2.5rem); text-shadow: 0px 1px 16px rgba(0, 0, 0, 0.4);">
        Игра с коробками
      </p>
      <p style="max-width: 80rem; padding-bottom: 20px; font-size: clamp(1rem, 2vw, 1.5rem); text-shadow: 0px 1px 16px rgba(0, 0, 0, 0.4);">
        Есть три коробки: в одной лежат только яблоки, в другой — только апельсины, а в третьей — и яблоки, и апельсины. Однако все коробки подписаны неправильно: на коробке с яблоками не может быть написано "яблоки", на коробке с апельсинами — "апельсины", и на коробке с обоими фруктами — "яблоки и апельсины". Вам можно достать только один фрукт из любой коробки и по нему определить содержимое остальных.
        <b>Опишите алгоритм, как гарантированно определить, что находится в каждой коробке.</b>
        <br><br>
        <b style="color: #992211;">
          Вы можете открыть только одну коробку!
        </b>
      </p>
      <div v-if="game" class="box-container mobile">
        <box
          v-for="(b, index) in game.boxes"
          :key="index"
          :label="b.label"
          :is-open="b.isOpen"
          :content="b.content"
          :took="b.took"
          :prediction="b.prediction"
          :show-prediction="game.firstOpenedIndex !== null && index !== game.firstOpenedIndex"
          :can-change-prediction="canChangePrediction"
          @click="handleBoxClick(index)"
          @prediction-change="handlePredictionChange(index, $event)"
        />
      </div>
      <div
        class="button-container"
        :class="{ visible: isButtonVisible }"
      >
        <button class="button" style="background-color: #023E8A; margin-bottom: 40px;" @click="handleCheck">
          Проверить
        </button>
      </div>
      <TWallpaper ref="twallpaper" :options="options" />
    </div>
    <notification />
  </div>
</template>

<style scoped>
button {
  padding: clamp(12px, 2.5vw, 24px) clamp(24px, 4vw, 36px);
  font-size: clamp(16px, 2vw, 18px);
}
@keyframes fadeIn {
  from { opacity: 0; }
  to { opacity: 1; }
}
@media screen and (max-width: 850px) {
  .mobile {
    flex-direction: column;
    gap: clamp(10px, 2vw, 20px);
  }
}
.text {
  font-size: clamp(1rem, 5vw, 3rem);
  text-shadow: 0px 1px 16px rgba(0, 0, 0, 0.4);
}
.button {
  display: flex;
  width: clamp(200px, 30vw, 220px);
  justify-content: center;
  border: none;
  color: #fff;
  background-color: #9BC53D;
  border-radius: 8px;
  cursor: pointer;
  padding: 10px;
}
.centered-container {
  user-select: none;
  width: 80%;
  margin: auto;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
  text-align: center;
}
.box-container {
  display: flex;
  justify-content: center;
}
.button-container {
  opacity: 0;
  min-height: 100px;
}
.button-container.visible {
  opacity: 1;
}
.fullscreen {
  height: 100vh;
  align-items: center;
  justify-content: center;
  user-select: none;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  display: flex;
  font-size: clamp(32px, 5vw, 48px);
  z-index: 1000;
  animation: fadeIn 1s ease-in;
}
.loss-screen {
  background-color: #404E4D;
  color: #fff;
}
.win-screen {
  background-color: #9BC53D;
  color: #fff;
}
</style>

// src/App.tsx
// src/App.tsx
import './App.css';
import React, { useState, useEffect } from 'react';
import BoxComponent from './BoxComponent';
import { FruitGame, FruitsEnum, YouLostError } from './game';

const STORAGE_KEY = 'fruitGameState';

const App: React.FC = () => {
    const [game, setGame] = useState<FruitGame | null>(null);
    const [gameState, setGameState] = useState<'playing' | 'won' | 'lost'>('playing');

    // Загрузка игры из localStorage при первом рендере
    useEffect(() => {
        const savedState = localStorage.getItem(STORAGE_KEY);
        if (savedState) {
            try {
                const json = JSON.parse(savedState);
                const loadedGame = FruitGame.fromJSON(json.game);
                setGame(loadedGame);
                setGameState(json.gameState);
                return;
            } catch (error) {
                console.error('Ошибка при загрузке сохранённого состояния:', error);
            }
        }
        // Если сохранённого состояния нет или произошла ошибка, начинаем новую игру
        const newGame = new FruitGame();
        setGame(newGame);
        setGameState('playing');
    }, []);

    // Сохранение игры в localStorage при каждом изменении
    useEffect(() => {
        if (game) {
            const stateToSave = {
                game: game.toJSON(),
                gameState: gameState,
            };
            localStorage.setItem(STORAGE_KEY, JSON.stringify(stateToSave));
        }
    }, [game, gameState]);

    const handleBoxClick = (index: number) => {
        if (!game || gameState !== 'playing') return;
        try {
            game.open(index);
            const newGame = game.clone();
            setGame(newGame);

            if (newGame._boxes.every((box) => box.isOpen)) {
                // Проверяем, выиграл ли пользователь
                const isWin = newGame.checkWin();
                setGameState(isWin ? 'won' : 'lost');
            }
        } catch (error: any) {
            if (error instanceof YouLostError) {
                setGameState('lost');
            } else {
                alert(error.message);
            }
        }
    };

    const handlePredictionChange = (index: number, value: FruitsEnum) => {
        if (!game || gameState !== 'playing') return;
        const numBoxesOpened = game._boxes.filter((box) => box.isOpen).length;
        if (numBoxesOpened < 2) {
            try {
                game.setPrediction(index, value);
                const newGame = game.clone();
                setGame(newGame);
            } catch (error: any) {
                alert(error.message);
            }
        } else {
            alert('Вы больше не можете менять свой выбор');
        }
    };

    const handleRestart = () => {
        localStorage.removeItem(STORAGE_KEY);
        const newGame = new FruitGame();
        setGame(newGame);
        setGameState('playing');
    };

    if (!game) {
        return <div>Загрузка...</div>;
    }

    const numBoxesOpened = game._boxes.filter((box) => box.isOpen).length;
    const canChangePrediction = numBoxesOpened < 2 && gameState === 'playing';

    return (
        <div style={{ textAlign: 'center', userSelect: 'none' }}>
            <h1>Игра с коробками</h1>
            <p style={{ maxWidth: '600px', margin: '0 auto' }}>
                Есть три коробки: в одной лежат только яблоки, в другой — только апельсины, а в третьей — и
                яблоки, и апельсины. Однако все коробки подписаны неправильно: на коробке с яблоками не может
                быть написано "яблоки", на коробке с апельсинами — "апельсины", и на коробке с обоими фруктами
                — "яблоки и апельсины". Вам можно достать только один фрукт из любой коробки и по нему
                определить, что находится в остальных коробках.
                <p>Опишите алгоритм, как гарантированно определить, что находится в каждой коробке.</p>
                <b style={{ color: '#992211' }}>
                    У вас есть всего одна попытка! <br></br>Прежде чем открывать первую коробку, попробуйте
                    определить, что находится в остальных коробках, так как начать заново нельзя!
                </b>
            </p>

            <div style={{ display: 'flex', justifyContent: 'center', marginTop: '50px' }}>
                {game._boxes.map((box, index) => (
                    <BoxComponent
                        key={index}
                        label={box.label}
                        isOpen={box.isOpen}
                        content={box.content}
                        prediction={box.prediction}
                        took={box.took}
                        onClick={() => handleBoxClick(index)}
                        onPredictionChange={(value) => handlePredictionChange(index, value)}
                        showPrediction={game.indexOpenedBox !== null && index !== game.indexOpenedBox}
                        canChangePrediction={canChangePrediction}
                    />
                ))}
            </div>
            {gameState === 'won' && <h2>Поздравляем! Вы победили!</h2>}
            {gameState === 'lost' && <h2>К сожалению, вы проиграли.</h2>}
            {/* {(gameState === 'won' || gameState === 'lost') && (
                <button onClick={handleRestart}>Начать заново</button>
            )} */}
        </div>
    );
};

export default App;
